#公用配置
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#Spring 配置
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #配置文件上传
  servlet:
    multipart:
      #默认 为true允许附件上传
      enabled: true
      #临时文件存储位置
      #location: opt/tmp/file
      #设定一定大小文件就先写到临时文件中 0为不设定阈值
      file-size-threshold: 0
      #单个文件最大长度
      max-file-size: 5MB
      #单次Request 請求允许的最大文件长度
      max-request-size:  10MB
  #视图配置
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    suffix: .ftl

  #热部署 重启 #热部署扫包位置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mydatabase?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      password: 123456
      username: sinbad
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 5
      #最大连接池数量
      max-active: 100
      #最小连接池数量
      min-idle: 5
      #有两个含义：1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 20000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictableIdle-time-millis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: SELECT '1' FROM DUAL
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis 执行validationQuery检测连接是否有效
      test-whileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。 在Druid中，不会存在Oracle下PSCache占用内存过多的问题 可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: 100
      #关闭 abanded 连接时输出错误日志
      log-abandoned: true
      time-between-connect-error-millis: 100
      #支持表情
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,  'wall'用于防火墙
      filter:
        slf4j:
          enabled: true
        commons-log:
          enabled: true
        log4j:
          connection-log-enabled: true
        wall:
          config:
            use-allow: true
            multi-statement-allow: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 300
          merge-sql: true
          enabled: true
          connection-stack-trace-enable: true
          db-type: mysql
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/monitor/druid/*"
        session-stat-enable: true
        profile-enable: true
        session-stat-max-count: 1000

  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true




mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.sinbad.boot.druid.monitor.entity

#日志
logging:
  config: classpath:logconfig/logback.xml
  file:
    path: /home/sinbad/work/workspace/log/boot-druid-monitor


